#!/usr/bin/env bash
set -euo pipefail
root="${1:?source tree required}"
contract_h="$root/tools/manager/infiltratorfs-manager-contract.h"
contract_c="$root/tools/manager/infiltratorfs-manager-contract.c"
linux="$root/tools/infiltratorfs-manager.c"
windows="$root/tools/windows/infiltratorfs-windows.c"
cmake="$root/CMakeLists.txt"

test -f "$contract_h"
test -f "$contract_c"
grep -Fq 'INFILFS_MANAGER_ACTION_INSPECT' "$contract_h"
grep -Fq 'INFILFS_MANAGER_ACTION_CHECK' "$contract_h"
grep -Fq 'INFILFS_MANAGER_ACTION_SCRUB' "$contract_h"
grep -Fq 'INFILFS_MANAGER_ACTION_FORENSIC' "$contract_h"
grep -Fq '"Filesystem management"' "$contract_c"
grep -Fq '"Mount and Open"' "$contract_c"
grep -Fq '"Erase and format"' "$contract_c"
grep -Fq 'manager/infiltratorfs-manager-contract.h' "$linux"
grep -Fq '../manager/infiltratorfs-manager-contract.h' "$windows"
grep -Fq 'tools/manager/infiltratorfs-manager-contract.c' "$cmake"
grep -Fq 'IDC_CHECK' "$windows"
grep -Fq 'IDC_FORENSIC' "$windows"
grep -Fq 'infs_check(&g_volume' "$windows"
grep -Fq 'infs_forensic_scan(' "$windows"
grep -Fq 'create_image_dialog' "$windows"
grep -Fq 'show_page(0)' "$windows"
grep -Fq 'palette->connection_rgb' "$windows"
grep -Fq 'palette->heading_rgb' "$windows"
grep -Fq 'palette->warning_muted_rgb' "$windows"
grep -Fq 'struct infilfs_manager_state' "$contract_h"
grep -Fq 'infilfs_manager_compute_enablement' "$contract_c"
grep -Fq 'infilfs_manager_format_capacity' "$contract_c"
grep -Fq '.ready_status = "Ready"' "$contract_c"
grep -Fq '.mounted_status = "Mounted"' "$contract_c"
grep -Fq '.unmounted_status = "Not mounted"' "$contract_c"
grep -Fq '.unknown_filesystem = "Unknown / unformatted"' "$contract_c"
grep -Fq '.default_image_name = "infiltratorfs.img"' "$contract_c"
grep -Fq 'action->success' "$linux"
grep -Fq 'infilfs_manager_compute_enablement' "$linux"
grep -Fq 'infilfs_manager_compute_enablement' "$windows"
grep -Fq 'infilfs_manager_format_capacity' "$windows"
! grep -Fq 'format_gib_wide' "$windows"
! grep -Fq 'L"Unknown / unformatted"' "$windows"
! grep -Fq 'L"infiltratorfs.img"' "$windows"
echo "manager-parity-policy: PASS"
