#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
set -euo pipefail

root="${1:?source tree required}"
archive="$root/assets/fonts/mb-corpo-fonts.tar.xz"
test -f "$archive"
manager="$root/tools/infiltratorfs-manager.c"
windows="$root/tools/windows/infiltratorfs-windows.c"
windows_entry="$root/tools/windows/infiltratorfs-windows-entry.c"
resource="$root/tools/windows/infiltratorfs-windows-fonts.rc.in"
cmake="$root/CMakeLists.txt"

grep -Fq 'InfiltratrTypographyAssets.cmake' "$cmake"
grep -Fq 'INFILTRATR_MB_CORPO_ARCHIVE_SHA256' "$cmake"
grep -Fq 'INFILTRATR_MB_CORPO_BRAND_REGULAR_FILE' "$cmake"
grep -Fq 'INFILTRATR_MB_CORPO_UI_BOLD_FILE' "$cmake"
grep -Fq 'INFILTRATR_MB_CORPO_UI_REGULAR_FILE' "$cmake"
grep -Fq 'INFILTRATR_MB_CORPO_BRAND_REGULAR_SHA256' "$cmake"
grep -Fq 'INFILTRATR_MB_CORPO_UI_BOLD_SHA256' "$cmake"
grep -Fq 'INFILTRATR_MB_CORPO_UI_REGULAR_SHA256' "$cmake"
grep -Fq 'DESTINATION share/fonts/truetype/infiltratorfs' "$cmake"
grep -Fq '@INFILFS_FONT_A_COND_REGULAR_RC@' "$resource"
grep -Fq '@INFILFS_FONT_S_BOLD_RC@' "$resource"
grep -Fq '@INFILFS_FONT_S_REGULAR_RC@' "$resource"

grep -Fq '#include <gtk/gtk.h>' "$manager"
grep -Fq '#include "infiltratr/design.h"' "$manager"
grep -Fq '#include "infiltratr/format.h"' "$manager"
grep -Fq 'infiltratr_theme_resolve' "$manager"
grep -Fq 'infiltratr_theme_mode_next' "$manager"
grep -Fq 'infiltratr_format_disk_capacity' "$manager"
grep -Fq 'infiltratr_typography' "$manager"
grep -Fq 'infiltratr_design_metrics' "$manager"
grep -Fq 'InfiltratrProjectInfo' "$manager"
grep -Fq 'infiltratr_realpath_copy' "$manager"
grep -Fq '@UI_FONT@' "$manager"
grep -Fq '@BRAND_FONT@' "$manager"
grep -Fq '@UI_BOLD@' "$manager"
grep -Fq '@ACCENT@' "$manager"
grep -Fq 'Cycle Infiltratr Common System, Day and Night themes' "$manager"
grep -Fq 'border-left-color:' "$manager"
grep -Fq 'button, button label, button image' "$manager"
grep -Fq 'palette->success_rgb' "$manager"
grep -Fq 'palette->warning_rgb' "$manager"
grep -Fq 'palette->info_rgb' "$manager"
grep -Fq 'palette->operation_rgb' "$manager"
grep -Fq 'palette->operation_hover_rgb' "$manager"
grep -Fq 'palette->titlebar_rgb' "$manager"
grep -Fq 'palette->connection_rgb' "$manager"
grep -Fq 'palette->connection_border_rgb' "$manager"
grep -Fq 'palette->heading_rgb' "$manager"
grep -Fq 'palette->summary_rgb' "$manager"
grep -Fq 'palette->kicker_rgb' "$manager"
grep -Fq 'palette->detail_label_rgb' "$manager"
grep -Fq 'palette->note_rgb' "$manager"
grep -Fq 'palette->status_border_rgb' "$manager"
grep -Fq 'palette->accent_foreground_rgb' "$manager"
grep -Fq 'palette->accent_hover_rgb' "$manager"
grep -Fq 'palette->selected_summary_rgb' "$manager"
grep -Fq 'palette->warning_muted_rgb' "$manager"
grep -Fq 'palette->warning_border_rgb' "$manager"
grep -Fq 'palette->success_border_rgb' "$manager"
grep -Fq '@ACCENT_FG@' "$manager"
grep -Fq '@ACCENT_HOVER@' "$manager"
grep -Fq '@SELECTED_SUMMARY@' "$manager"
grep -Fq '"stat-status"' "$manager"
grep -Fq '"action-check"' "$manager"
grep -Fq '"action-scrub"' "$manager"
grep -Fq '"section-danger"' "$manager"
grep -Fq 'headerbar button label, headerbar button image' "$manager"
! grep -Fq 'font-family: monospace' "$manager"
! grep -Fq 'Segoe UI' "$manager"
! grep -Fq 'Sans' "$manager"
! grep -Eq 'python3|PyGObject|gi\.repository|FcConfigAppFontAddFile' "$manager"
! grep -Fq 'infiltratorfs-theme' "$manager"

grep -Fq 'gtk_about_dialog_set_logo' "$manager"
grep -Fq 'gtk_icon_theme_load_icon' "$manager"
grep -Fq '"drive-harddisk", 96' "$manager"
grep -Fq 'gtk_about_dialog_set_website_label' "$manager"
grep -Fq 'link-about-dialog' "$manager"
grep -Fq 'INFILTRATORFS · NATIVE FILESYSTEM' "$manager"

grep -Fq 'AddFontMemResourceEx' "$windows"
grep -Fq 'RemoveFontMemResourceEx' "$windows"
grep -Fq 'infiltratr_typography' "$windows"
grep -Fq 'infiltratr_format_scaled_quantity' "$windows"
grep -Fq 'format_gib_wide' "$windows"
grep -Fq 'create_common_font' "$windows"
! grep -Fq '1024.0 * 1024.0 * 1024.0' "$windows"
! grep -Fq 'L"Segoe UI"' "$windows"
! grep -Fq 'L"Consolas"' "$windows"

grep -Fq '#include "infiltratr/design.h"' "$windows"
grep -Fq 'infiltratr_theme_resolve' "$windows"
grep -Fq 'INFILTRATR_THEME_SYSTEM' "$windows"
grep -Fq 'INFILTRATR_THEME_DAY' "$windows"
grep -Fq 'INFILTRATR_THEME_NIGHT' "$windows"
grep -Fq 'L"ThemeMode"' "$windows"
grep -Fq 'IDM_VIEW_THEME_SYSTEM' "$windows"
! grep -Fq 'infs_mb_rgb_map' "$windows_entry"
! grep -Fq '#define RegGetValueW' "$windows_entry"
